# Generated by Django 5.1.1 on 2024-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("past_chess", "0006_game_black_moves_comments_game_white_moves_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="black_moves_comments",
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="white_moves_comments",
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
    ]
