# Generated by Django 5.1.1 on 2024-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=150)),
                ("site", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("round", models.CharField(max_length=200)),
                ("white", models.CharField(max_length=200)),
                ("black", models.CharField(max_length=200)),
                ("result", models.CharField(max_length=200)),
                ("tag_pairs", models.JSONField()),
                ("white_moves", models.CharField(max_length=1024)),
                ("black_moves", models.CharField(max_length=1024)),
            ],
        ),
    ]
