# Generated by Django 5.1.1 on 2024-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("past_chess", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="black",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="black_moves",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="event",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="result",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="round",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="site",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="tag_pairs",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="white",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="white_moves",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
