# Generated by Django 5.1.1 on 2024-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("past_chess", "0002_alter_game_black_alter_game_black_moves_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="black",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="black_moves",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="event",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="result",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="round",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="site",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="tag_pairs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="white",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="white_moves",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
