# Generated by Django 5.1.1 on 2024-10-09 11:51

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("past_chess", "0004_add_hstore_extension"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="tag_pairs",
        ),
        migrations.AddField(
            model_name="game",
            name="tag_pairs",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True
            ),
        ),
    ]
